In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv("C:\\SourceFiles\\Sales_add.csv")

In [5]:
df.head()

Month      Region      Manager  Sales_before_digital_add(in $)  \
0  Month-1  Region - A  Manager - A                          132921   
1  Month-2  Region - A  Manager - C                          149559   
2  Month-3  Region - B  Manager - A                          146278   
3  Month-4  Region - B  Manager - B                          152167   
4  Month-5  Region - C  Manager - B                          159525   

   Sales_After_digital_add(in $)  
0                         270390  
1                         223334  
2                         244243  
3                         231808  
4                         258402

In [6]:
df.shape

(22, 5)

In [8]:
df.columns

Index(['Month', 'Region', 'Manager', 'Sales_before_digital_add(in $)',
       'Sales_After_digital_add(in $)'],
      dtype='object')

# 1. The company wishes to clarify whether there is any increase in sales after
 # stepping into digital marketing.


# Step 1: State the hypotheses

In [ ]:
H0 :  No difference in sales after stepping into digital marketing
H0 :  Significance  difference in sales after stepping into digital marketing    

# Step2 : going with a t-test, and let’s just set α=0.05 for now.

In [9]:
from scipy  import stats

In [11]:
before_digital=df['Sales_before_digital_add(in $)']

In [12]:
after_digital=df['Sales_After_digital_add(in $)']

In [13]:
from scipy import stats

t_value,p_value=stats.ttest_ind(before_digital,after_digital)

print('Test statistic is %f'%float("{:.6f}".format(t_value)))

print('p-value for two tailed test is %f'%p_value)

alpha = 0.05



Test statistic is -12.995084
p-value for two tailed test is 0.000000


In [21]:
if p_value<=alpha:
    print("We reject null hypothesis, So we conclude that the    there is significance change in sales after stepping into digitalizaton")
else:
    print("Failed to reject null hypothesis")

We reject null hypothesis, So we conclude that the    there is significance change in sales after stepping into digitalizaton


# 2. The company needs to check whether there is any dependency between the features “Region” and “Manager”

In [ ]:
H0:  There is no dependency between the features Region and Manager
H1:  There is dependency between the features REgion and Manager

In [23]:
data_df=df[['Region', 'Manager']]

In [24]:
data_df.head

<bound method NDFrame.head of         Region      Manager
0   Region - A  Manager - A
1   Region - A  Manager - C
2   Region - B  Manager - A
3   Region - B  Manager - B
4   Region - C  Manager - B
5   Region - A  Manager - B
6   Region - C  Manager - C
7   Region - A  Manager - A
8   Region - B  Manager - C
9   Region - C  Manager - B
10  Region - B  Manager - C
11  Region - A  Manager - A
12  Region - B  Manager - A
13  Region - A  Manager - A
14  Region - C  Manager - A
15  Region - A  Manager - B
16  Region - A  Manager - C
17  Region - C  Manager - B
18  Region - B  Manager - A
19  Region - A  Manager - B
20  Region - B  Manager - A
21  Region - A  Manager - C>

In [29]:
contingency_table=pd.crosstab(df["Region"],df["Manager"])
print('contingency_table :-\n',contingency_table)


contingency_table :-
 Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1


In [30]:
#Observed Values
Observed_Values = contingency_table.values 
print("Observed Values :-\n",Observed_Values)


Observed Values :-
 [[4 3 3]
 [4 1 2]
 [1 3 1]]


In [31]:
b=stats.chi2_contingency(contingency_table)
Expected_Values = b[3]
print("Expected Values :-\n",Expected_Values)
no_of_rows=len(contingency_table.iloc[0:2,0])
no_of_columns=len(contingency_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05


Expected Values :-
 [[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]
Degree of Freedom:- 1


In [32]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:-",chi_square_statistic)
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('chi-square statistic:',chi_square_statistic)
print('critical_value:',critical_value)
print('p-value:',p_value)
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")


chi-square statistic:- 2.921995464852608
critical_value: 3.841458820694124
p-value: 0.08737974495299139
Significance level:  0.05
Degree of Freedom:  1
chi-square statistic: 2.921995464852608
critical_value: 3.841458820694124
p-value: 0.08737974495299139
Retain H0,There is no relationship between 2 categorical variables
Retain H0,There is no relationship between 2 categorical variables
